[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
research_sol = "7AX5ZbemiAUG4WVdh12stGpsS6E4W8WeCbcDpLiyoWE4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ritikbhatt020/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
